project_id = "ihvnriqsrdhayysfcywm"

[functions.send-verification-code]
verify_jwt = false

[functions.verify-code]
verify_jwt = false

[functions.complete-room]
verify_jwt = true

[functions.send-gift]
verify_jwt = true

[functions.claim-gift]
verify_jwt = true