// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ihvnriqsrdhayysfcywm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlodm5yaXFzcmRoYXl5c2ZjeXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NDUyNjMsImV4cCI6MjA3MDUyMTI2M30.FKz9vGkKdeGl8cCN4Ta6FYdpLMWkCLZ9siodb-ihdvI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});